version: '3'

services:
  redis:
    image: redis:alpine
    networks:
      - backend

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  vote:
    build: ./vote
    ports:
      - "5000:80"
    networks:
      - frontend
      - backend

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - frontend
      - backend

  worker:
    build: ./worker
    networks:
      - backend

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  db-data:
